baseURL: "https://wertyuii.netlify.app/"
languageCode: 'en-us'
title: 'DataFirst'
theme: 'PaperMod'

params:
      homeInfoParams: 
            Title: 'Notes on Data, Product & Generative AI📓'
            content: A collection of scientific methods, processes, algorithms, and systems to build stories & models.
      SocialIcons:
          -  name: twitter
             url: https://twitter.com/
          -  name: github
             url: https://github.com/
          -  name: linkedin
             url: https://linkedin.com/
      ShowBreadCrumbs: true
      ShowReadingTime: true
      ShowPostNavLinks: true

menu:
    main:
      - identifier: Posts
        name: Posts
        url: /posts/
        weight: 10
      - identifier: Tags
        name: Tags
        url: /tags/
        weight: 20
      - identifier: Archives
        name: Archives
        url: /archives/
        weight: 20
